# Importing Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/accepted_2007_to_2018Q4.csv", low_memory=False)
df.shape

(2260701, 151)

# Data Description

In [3]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260639e+06,2.260668e+06,...,10917.0,10917.000000,10917.0,10917.000000,8651.000000,10917.000000,10917.000000,34246.000000,34246.000000,34246.000000
mean,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,3.068792e-01,6.985882e+02,...,3.0,155.045981,3.0,13.743886,454.798089,11636.883942,193.994321,5010.664267,47.780365,13.191322
std,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,8.672303e-01,3.301038e+01,...,0.0,129.040594,0.0,9.671178,375.385500,7625.988281,198.629496,3693.122590,7.311822,8.159980
min,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,0.000000e+00,6.750000e+02,...,3.0,59.440000,3.0,5.000000,175.230000,5627.000000,44.440000,2208.000000,45.000000,6.000000
50%,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,...,3.0,119.140000,3.0,15.000000,352.770000,10028.390000,133.160000,4146.110000,45.000000,14.000000
75%,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,0.000000e+00,7.150000e+02,...,3.0,213.260000,3.0,22.000000,620.175000,16151.890000,284.190000,6850.172500,50.000000,18.000000
max,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [6]:
df.isna().sum()

id                             0
member_id                2260701
loan_amnt                     33
funded_amnt                   33
funded_amnt_inv               33
                          ...
settlement_status        2226455
settlement_date          2226455
settlement_amount        2226455
settlement_percentage    2226455
settlement_term          2226455
Length: 151, dtype: int64

# Handling Missing Values

In [7]:
# Drop columns with ≥50% missing values
null_percent = df.isnull().mean() * 100
high_null_cols = null_percent[null_percent >= 50]
print("No. of colums with >=50% null values:", len(high_null_cols))

df = df.drop(columns=high_null_cols.index)
print(f"Remaining columns: {df.shape[1]}")

No. of colums with >=50% null values: 44
Remaining columns: 107

| Column                                                                                         | Reason                                                        |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| `id`                                                                                           | Just a unique identifier                                      |
| `emp_title`                                                                                    | Free-text, unstructured job title                             |
| `title`                                                                                        | User-provided loan title (redundant, high cardinality)        |
| `url`                                                                                          | Obsolete/irrelevant                                           |
| `zip_code`                                                                                     | Partially masked → low value, high leakage risk               |
| `addr_state`                                                                                   | Could bias the model geographically (optional to drop)        |
| `earliest_cr_line`                                                                             | Date as string → better to convert to derived feature         |
| `application_type`                                                                             | Most entries are "Individual", low variance                   |
| `policy_code`                                                                                  | Constant = 1, no variance                                     |
| `issue_d`, `last_pymnt_d`, `last_credit_pull_d`, `next_pymnt_d`                                | Temporal leakage: not available at loan origination           |
| `pymnt_plan`                                                                                   | Almost always 'n', low variance                               |
| `out_prncp`, `out_prncp_inv`, `total_pymnt`, `recoveries`, `collection_recovery_fee`           | Post-loan info → data leakage                                 |
| `loan_status`, `funded_amnt`, `funded_amnt_inv`                                                | Correlated with outcome or future status                      |
| `member_id`                                                                                    | 100% null, already dropped                                    |
| `total_pymnt_inv`, `total_rec_prncp`, `total_rec_int`, `total_rec_late_fee`, `last_pymnt_amnt` | Post-loan → Data leakage                                      |
| `last_fico_range_high`, `last_fico_range_low`                                                  | After disbursement → leakage                                  |
| `collections_12_mths_ex_med`                                                                   | Almost always 0 (check distribution)                          |
| `acc_now_delinq`, `delinq_amnt`, `num_tl_120dpd_2m`, `num_tl_30dpd`, `num_tl_90g_dpd_24m`      | Too sparse or duplicate of better vars                        |
| `chargeoff_within_12_mths`, `tax_liens`                                                        | Too sparse or low signal (EDA confirms)                       |
| `disbursement_method`                                                                          | Almost always "Cash"                                          |
| `hardship_flag`, `debt_settlement_flag`                                                        | Post-loan hardship → target leakage                           |
| `pub_rec_bankruptcies`                                                                         | Can keep if clean, but usually sparsely filled (EDA required) |

In [8]:
# Drop obvious columns
drop_cols = ['id', 'emp_title', 'title', 'url', 'zip_code', 'addr_state', 'earliest_cr_line', 'application_type',
    'policy_code', 'issue_d', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d',
    'pymnt_plan', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 
    'recoveries', 'collection_recovery_fee', 'loan_status', 'funded_amnt', 
    'funded_amnt_inv', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'last_pymnt_amnt', 'last_fico_range_high',
    'last_fico_range_low', 'collections_12_mths_ex_med', 'acc_now_delinq', 'delinq_amnt', 'num_tl_120dpd_2m',
    'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'chargeoff_within_12_mths', 'tax_liens', 
    'disbursement_method', 'hardship_flag', 'debt_settlement_flag', 'pub_rec_bankruptcies', 
    'pub_rec_bankruptcies'
]
df = df.drop(columns=[col for col in drop_cols if col in df.columns])
df.shape

(2260701, 67)

In [9]:
missing_info = pd.Series()
for col in df.isna().sum().index:
    if df[col].isna().sum() > 0:
        missing_info[col] = df[col].isna().sum()
print(missing_info)

loan_amnt                        33
term                             33
int_rate                         33
installment                      33
grade                            33
                              ...
percent_bc_gt_75              75412
tot_hi_cred_lim               70309
total_bal_ex_mort             50063
total_bc_limit                50063
total_il_high_credit_limit    70309
Length: 67, dtype: int64

In [10]:
# 1. Drop 33 rows with core nulls
df = df.dropna(subset=['loan_amnt', 'term', 'int_rate'])

# 2. Impute low-null numerical features
num_impute_cols = ['annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 
                   'open_acc', 'pub_rec', 'total_acc', 'revol_util']
for col in num_impute_cols:
    df[col] = df[col].fillna(df[col].median())

# 3. Impute categorical with 'unknown'
df['emp_length'] = df['emp_length'].fillna('unknown')

# 4. Drop high-missing features
drop_high_nulls = ['open_acc_6m', 'open_il_12m', 'open_il_24m', 'total_bal_il', 
                   'il_util', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'open_act_il',
                   'max_bal_bc', 'all_util', 'mo_sin_old_il_acct', 'mths_since_rcnt_il',
                   'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim',
                   'acc_open_past_24mths', 'avg_cur_bal', 'bc_util', 'bc_open_to_buy',
                   'mo_sin_rcnt_rev_tl_op', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_tl',
                   'mths_since_recent_bc', 'mths_since_recent_inq', 'num_accts_ever_120_pd',
                   'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl',
                   'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0',
                   'num_sats', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
                   'tot_hi_cred_lim', 'total_bc_limit', 'total_bal_ex_mort',
                   'total_il_high_credit_limit', 'mort_acc']
df.drop(columns=drop_high_nulls, inplace=True)
df.shape

(2260668, 24)

In [11]:
df.isna().sum()

loan_amnt                   0
term                        0
int_rate                    0
installment                 0
grade                       0
sub_grade                   0
emp_length                  0
home_ownership              0
annual_inc                  0
verification_status         0
purpose                     0
dti                         0
delinq_2yrs                 0
fico_range_low              0
fico_range_high             0
inq_last_6mths              0
open_acc                    0
pub_rec                     0
revol_bal                   0
revol_util                  0
total_acc                   0
initial_list_status         0
open_rv_12m            866129
open_rv_24m            866129
dtype: int64

In [12]:
df[["open_rv_12m", "open_rv_24m"]].value_counts()

open_rv_12m  open_rv_24m
0.0          0.0            223783
             1.0            153935
1.0          1.0            143952
             2.0            124839
0.0          2.0             76342
                             ...
26.0         32.0                1
             37.0                1
27.0         28.0                1
28.0         28.0                1
             30.0                1
Name: count, Length: 477, dtype: int64

In [13]:
df[["open_rv_12m", "open_rv_24m"]].describe()

        open_rv_12m   open_rv_24m
count  1.394539e+06  1.394539e+06
mean   1.290133e+00  2.749923e+00
std    1.506827e+00  2.596911e+00
min    0.000000e+00  0.000000e+00
25%    0.000000e+00  1.000000e+00
50%    1.000000e+00  2.000000e+00
75%    2.000000e+00  4.000000e+00
max    2.800000e+01  6.000000e+01

In [14]:
df[["open_rv_12m", "open_rv_24m"]].nunique()

open_rv_12m    29
open_rv_24m    50
dtype: int64

In [15]:
df['open_rv_12m'] = df['open_rv_12m'].fillna(0.0)
df['open_rv_24m'] = df['open_rv_24m'].fillna(0.0)
df.isna().sum()

loan_amnt              0
term                   0
int_rate               0
installment            0
grade                  0
sub_grade              0
emp_length             0
home_ownership         0
annual_inc             0
verification_status    0
purpose                0
dti                    0
delinq_2yrs            0
fico_range_low         0
fico_range_high        0
inq_last_6mths         0
open_acc               0
pub_rec                0
revol_bal              0
revol_util             0
total_acc              0
initial_list_status    0
open_rv_12m            0
open_rv_24m            0
dtype: int64

In [16]:
df.to_csv("../data/processed/loans_processed.csv", index=False)